/**
 * The only HTTP calls the frontend makes: the room service (src/roxstar/token_server.py).
 *   POST /rooms  creates a real LiveKit room and returns its code
 *   POST /token  returns a token for one room, and brings the AI worker into that room
 */
import type { Session } from '../types/room';

const RAW_URL = (import.meta.env.VITE_TOKEN_URL as string | undefined) ?? 'http://127.0.0.1:8000';
const BASE_URL =
  RAW_URL.startsWith('http://') || RAW_URL.startsWith('https://') ? RAW_URL : `https://${RAW_URL}`;

export type JoinErrorKind = 'unreachable' | 'not_found' | 'name_taken' | 'invalid' | 'rejected';

export class JoinError extends Error {
  constructor(
    readonly kind: JoinErrorKind,
    message: string,
  ) {
    super(message);
  }
}

const KIND_BY_STATUS: Record<number, JoinErrorKind> = {
  400: 'invalid',
  404: 'not_found',
  409: 'name_taken',
};

async function post<T>(path: string, body: object): Promise<T> {
  let response: Response;
  try {
    response = await fetch(`${BASE_URL}${path}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    });
  } catch {
    throw new JoinError('unreachable', "Can't reach the Roxstar room service.");
  }
  const data = (await response.json().catch(() => ({}))) as T & { error?: string };
  if (!response.ok) {
    throw new JoinError(
      KIND_BY_STATUS[response.status] ?? 'rejected',
      data.error ?? 'The room service could not start a session.',
    );
  }
  return data;
}

/** Create a new room. The code is generated by the server, e.g. "tech-talk-8f3k". */
export async function createRoom(title: string): Promise<{ room: string; title: string }> {
  return post('/rooms', { title });
}

/**
 * Get a token for one room. "join" requires the room to exist and the name to be free in it;
 * "rejoin" is the same person coming back after a dropped connection.
 */
export async function requestSession(
  name: string,
  room: string,
  mode: 'join' | 'rejoin' = 'join',
): Promise<Session> {
  const data = await post<{ token?: string; url?: string; room?: string; title?: string }>('/token', {
    name,
    room,
    mode,
  });
  if (!data.token || !data.url) {
    throw new JoinError('rejected', 'The room service could not start a session.');
  }
  return {
    url: data.url,
    token: data.token,
    name,
    room: data.room ?? room,
    title: data.title ?? '',
  };
}
